field_map = {
    # API parameter               CMR keyword                       CMR format strings
    'absoluteOrbit':        {'key': 'orbit_number',            'fmt': '{0}'},
    'asfFrame':             {'key': 'attribute[]',             'fmt': 'int,FRAME_NUMBER,{0}',       'attr': 'FRAME_NUMBER'},
    'asfPlatform':          {'key': 'attribute[]',             'fmt': 'string,ASF_PLATFORM,{0}',    'attr': 'ASF_PLATFORM'},
    'maxBaselinePerp':      {'key': 'attribute[]',             'fmt': 'float,INSAR_BASELINE,,{0}',  'attr': 'INSAR_BASELINE'},
    'minBaselinePerp':      {'key': 'attribute[]',             'fmt': 'float,INSAR_BASELINE,{0},',  'attr': 'INSAR_BASELINE'},
    'bbox':                 {'key': 'bounding_box',            'fmt': '{0}'},
    'beamMode':             {'key': 'attribute[]',             'fmt': 'string,BEAM_MODE,{0}',       'attr': 'BEAM_MODE'},
    'beamSwath':            {'key': 'attribute[]',             'fmt': 'string,BEAM_MODE_TYPE,{0}',  'attr': 'BEAM_MODE_TYPE'},
    'campaign':             {'key': 'attribute[]',             'fmt': 'string,MISSION_NAME,{0}',    'attr': 'MISSION_NAME'},
    'maxDoppler':           {'key': 'attribute[]',             'fmt': 'float,DOPPLER,,{0}',         'attr': 'DOPPLER'},
    'minDoppler':           {'key': 'attribute[]',             'fmt': 'float,DOPPLER,{0},',         'attr': 'DOPPLER'},
    'maxFaradayRotation':   {'key': 'attribute[]',             'fmt': 'float,FARADAY_ROTATION,,{0}',        'attr': 'FARADAY_ROTATION'},
    'minFaradayRotation':   {'key': 'attribute[]',             'fmt': 'float,FARADAY_ROTATION,{0},',        'attr': 'FARADAY_ROTATION'},
    'flightDirection':      {'key': 'attribute[]',             'fmt': 'string,ASCENDING_DESCENDING,{0}',        'attr': 'ASCENDING_DESCENDING'},
    'flightLine':           {'key': 'attribute[]',             'fmt': 'string,FLIGHT_LINE,{0}',         'attr': 'FLIGHT_LINE'},
    'frame':                {'key': 'attribute[]',             'fmt': 'int,CENTER_ESA_FRAME,{0}',       'attr': 'CENTER_ESA_FRAME'},
    'granule_list':         {'key': 'readable_granule_name[]', 'fmt': '{0}'},
    'groupID':              {'key': 'attribute[]',             'fmt': 'string,GROUP_ID,{0}', 'attr': 'GROUP_ID'},
    'insarStackId':         {'key': 'attribute[]',             'fmt': 'int,INSAR_STACK_ID,{0}', 'attr': 'INSAR_STACK_ID'},
    'linestring':           {'key': 'line',                    'fmt': '{0}'},
    'lookDirection':        {'key': 'attribute[]',             'fmt': 'string,LOOK_DIRECTION,{0}', 'attr': 'LOOK_DIRECTION'},
    'maxInsarStackSize':    {'key': 'attribute[]',             'fmt': 'int,INSAR_STACK_SIZE,,{0}', 'attr': 'INSAR_STACK_SIZE'},
    'minInsarStackSize':    {'key': 'attribute[]',             'fmt': 'int,INSAR_STACK_SIZE,{0},', 'attr': 'INSAR_STACK_SIZE'},
    'instrument':           {'key': 'instrument[]',            'fmt': '{0}'},
    'offNadirAngle':        {'key': 'attribute[]',             'fmt': 'float,OFF_NADIR_ANGLE,{0}', 'attr': 'OFF_NADIR_ANGLE'},
    'platform':             {'key': 'platform[]',              'fmt': '{0}', 'attr': 'ASF_PLATFORM'},
    'polarization':         {'key': 'attribute[]',             'fmt': 'string,POLARIZATION,{0}', 'attr': 'POLARIZATION'},
    'point':                {'key': 'point',                   'fmt': '{0}'},
    'polygon':              {'key': 'polygon',                 'fmt': '{0}'},
    'processingDate':       {'key': 'updated_since',           'fmt': '{0}'},
    'processingLevel':      {'key': 'attribute[]',             'fmt': 'string,PROCESSING_TYPE,{0}', 'attr': 'PROCESSING_TYPE'},
    'product_list':         {'key': 'granule_ur[]',            'fmt': '{0}'},
    'provider':             {'key': 'provider',                'fmt': '{0}'},
    'relativeOrbit':        {'key': 'attribute[]',             'fmt': 'int,PATH_NUMBER,{0}', 'attr': 'PATH_NUMBER'},
    'temporal':             {'key': 'temporal',                'fmt': '{0}'}
}