name: Update changelog on Releases

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - stable

jobs:
  changelog-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog check
        uses: dangoslen/changelog-enforcer@v3.6.1
        with:
          changeLogPath: CHANGELOG.md
          skipLabels: bumpless
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
